baseURL = "https://tahoe-lafs.org"
title   = "Tahoe-LAFS"

defaultContentLanguage = "en"
languageCode = "en-us"

rssLimit  = 300
copyright = "This work is licensed under a Creative Commons Attribution-NonCommercial-ShareAlike 4.0 International License."

archetypeDir = "archetypes"
contentDir   = "content"
dataDir      = "data"
layoutDir    = "layouts"
publishDir   = "public"

buildDrafts  = false
buildFuture  = false
buildExpored = false
canonifyURLs = true

enableRobotsTXT = true
enableGitInfo   = true
enableEmoji     = true
enableMissingTranslationPlaceholders = true
disableRSS     = false
disableSitemap = false
disable404     = false
disableHugoGeneratorInject = true

pluralizeListTitles = false
paginate = 8

[permalinks]
  blog = "/blog/:filename/"

[author]
  name = "Tahoe-LAFS"
  email = "contact@tahoe-lafs.org"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
    [markup.goldmark.extensions]
      definitionList = true
      footnote = true

[taxonomies]
  tag      = "tags"
  category = "categories"

[params]
  dateform        = "Jan 2, 2006"
  dateformShort   = "Jan 2"
  dateformNum     = "2006-01-02"
  dateformNumTime = "2006-01-02 15:04"

  # Metadata mostly used in document's head
  description = "Tahoe-LAFS is a Free and Open decentralized cloud storage system."
  keywords = "public, developer, privacy, security, foss, floss, storage, system, cloud, decentralized, servers, files"
  images = [""]

  # Prefix of link to the git commit detail page. GitInfo must be enabled.
  gitUrl = "https://github.com/tahoe-lafs/new-website-prototype/commit/"

  # Set disableReadOtherPosts to true in order to hide the links to other posts.
  disableReadOtherPosts = false

  # Integrate Javascript files or stylesheets by adding the url to the external assets or by
  # linking local files with their path relative to the static folder, e.g. "css/styles.css"
  customCSS = []
  customJS  = []

  justifyContent = false
  contentTypeName = "blog"

  # Colors for favicons
  [params.favicon.color]
    mask = "#F05454"

  # Social icons
  [[params.social]]
    name = "github"
    url  = "https://github.com/tahoe-lafs"
  
  [[params.social]]
    name = "twitter"
    url  = "https://twitter.com/tahoelafs"
  
  [[params.social]]
    name = "linkedin"
    url  = "https://www.linkedin.com/in/"

[languages]
  [languages.en]
    subtitle  = ""
    weight    = 1
    copyright = 'Unless otherwise noted, content on this page is under a <a href="https://creativecommons.org/licenses/by-nc-sa/4.0/" target="_blank" rel="noopener" title="License">CC BY-NC-SA 4.0</a> license.'
  [[languages.en.menu.main]]
    identifier = "about"
    name       = "About"
    url        = "/about/"
    weight     = "1"
  [[languages.en.menu.main]]
    identifier = "features"
    name       = "Features"
    url        = "/features/"
    weight     = "2"
  [[languages.en.menu.main]]
    identifier = "documentation"
    name       = "Documentation"
    url        = "/docs/"
    weight     = "3"
  [[languages.en.menu.main]]
    identifier = "blog"
    name       = "Blog"
    url        = "/blog/"
    weight     = "4"
  [[languages.en.menu.footer]]
    identifier = "data-privacy"
    name       = "Data Privacy"
    url        = "/privacy"
    weight     = "1"
  [[languages.en.menu.footer]]
    identifier = "imprint"
    name       = "Imprint"
    url        = "/imprint"
    weight     = "2"

[privacy]
  [privacy.instagram]
    disable = false
    simple = true
  [privacy.twitter]
    disable = false
    enableDNT = true
    simple = false
  [privacy.vimeo]
    disable = false
    enableDNT = true
    simple = false
  [privacy.youtube]
    disable = false
    privacyEnhanced = true
